### ISSUE TITLE
Geocode derives to wrong values due to catx

### ISSUE THREAD

**Issue by kanchana-chandra** [kpwhri/HCSRNCensusDemogDec#5]
Hi Al,

The catx to derive geocode gives the concatenated value of county,state,tract instead of state, county tract. To get the correct value cats or || can be used in place of catx. Please suggest.

Thanks!
Kanchana

**Comment by alphonsederus2** [comment]
Thanks for drawing my attention here! I've made the recommended replacement from catx to cats.
